<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Give `paiements` the two columns every other layer already assumes.
 *
 * `PaiementEleve` declared `reference` and `type_paiement` fillable, but the
 * table had neither. The consequence was not subtle: `storePaiement` validates
 * `type_paiement` as **required** and then calls `create()`, so recording a
 * payment answered
 *
 *     SQLSTATE[HY000]: table paiements has no column named type_paiement
 *
 * every single time. The accountant could not register a payment at all.
 *
 * Both fields are load-bearing elsewhere:
 *
 *   - `type_paiement` is the motif. The accountant's form requires it, the
 *     receipt prints it, and two frontend pages read it — `FacturesPage` shows
 *     it as the invoice motif, `TransactionsPage` searches on it.
 *   - `reference` is generated by `PaymentController`, validated by
 *     `StorePaiementRequest` and `PaiementService`, exposed by
 *     `PaiementResource`, and carried by the `PaiementConfirmed` event. Without
 *     it, receipts fell back to `PAY-{id}` and reconciliation against a
 *     provider was impossible.
 *
 * Both nullable: existing rows have no value for either, and inventing one
 * would be worse than an honest blank.
 *
 * Not added: `statut`. The status column is `statut_global`, already present. A
 * second status field would be one more thing to keep in step, which is how
 * `ComptableController` and `DashboardController` ended up filtering on the
 * wrong one.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('paiements', function (Blueprint $table) {
            if (!Schema::hasColumn('paiements', 'reference')) {
                $table->string('reference')->nullable()->after('mode_paiement');
                $table->index('reference');
            }

            if (!Schema::hasColumn('paiements', 'type_paiement')) {
                $table->string('type_paiement')->nullable()->after('reference');
            }
        });
    }

    public function down(): void
    {
        Schema::table('paiements', function (Blueprint $table) {
            if (Schema::hasColumn('paiements', 'reference')) {
                $table->dropIndex(['reference']);
                $table->dropColumn('reference');
            }

            if (Schema::hasColumn('paiements', 'type_paiement')) {
                $table->dropColumn('type_paiement');
            }
        });
    }
};
